import type { Metadata } from "next";
import localFont from "next/font/local";
import Header from "@/components/sidebar/header";
import Footer from "@/components/footer/footer";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import "../globals.css";

const pretendard = localFont({
  src: "../../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const satoshi = localFont({
  src: "../../fonts/Satoshi-Variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${satoshi.variable}`}>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "14rem",
              "--sidebar-width-mobile": "14rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar />
          <SidebarInset>
            <div className="flex flex-col">
              <Header />
              <main className="w-full scrollbar-hide break-keep">{children}</main>
              <Footer />
            </div>
          </SidebarInset>
          <Analytics />
          <SpeedInsights />
        </SidebarProvider>

        <Toaster
          position="bottom-right"
          toastOptions={{
            classNames: {
              toast:
                "group toast group-[.toaster]:!rounded-full group-[.toaster]:!px-5 group-[.toaster]:!items-center group-[.toaster]:bg-background group-[.toaster]:text-foreground group-[.toaster]:!border-0 group-[.toaster]:shadow-lg",
              title: "group-[.toaster]:!text-sm group-[.toaster]:!font-bold",
              description: "group-[.toast]:!text-muted-foreground ",
              actionButton: "group-[.toast]:bg-primary group-[.toast]:text-primary-foreground",
              cancelButton: "group-[.toast]:bg-muted group-[.toast]:text-muted-foreground",
            },
          }}
          icons={{
            info: null,
          }}
          visibleToasts={1}
          expand
        />
      </body>
    </html>
  );
}
