import type { Metadata } from "next";
import localFont from "next/font/local";
import BreadCrumb from "@/components/sidebar/breadcrumb";
import Footer from "@/components/footer/footer";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { auth, signIn } from "@/auth";
import { AppSidebar } from "@/components/sidebar/app-sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";

import "../globals.css";

const pretendard = localFont({
  src: "../../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const satoshi = localFont({
  src: "../../fonts/Satoshi-Variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if (!session) await signIn("keycloak", { redirectTo: "/" });

  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${satoshi.variable}`}>
        <SidebarProvider
          style={
            {
              "--sidebar-width": "16rem",
              "--sidebar-width-mobile": "16rem",
            } as React.CSSProperties
          }
        >
          <AppSidebar />
          <SidebarInset>
            <div className="flex flex-col h-full">
              <header className="sticky top-0 z-30 flex h-16 shrink-0 items-center gap-2 border-b bg-background transition-[width,height] ease-linear group-has-[[data-collapsible=icon]]/sidebar-wrapper:h-12">
                <div className="flex w-full justify-between items-center gap-2 px-10 md:justify-start">
                  <SidebarTrigger className="-ml-1 pl-1.5 hidden md:block" />
                  <BreadCrumb />
                  <SidebarTrigger className="block md:hidden pl-1.5" />
                </div>
              </header>
              <main className="scrollbar-hide flex-1">{children}</main>
              <Footer />
            </div>
          </SidebarInset>

          <Analytics />
          <SpeedInsights />
        </SidebarProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}
