import type { Metadata } from "next";
import localFont from "next/font/local";
import MobileHeader from "@/components/header/mobileheader";
import Footer from "@/components/footer/footer";
import LenisProvider from "@/lib/lenisprovider";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { auth } from "@/auth";
import "../globals.css";

const pretendard = localFont({
  src: "../../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const satoshi = localFont({
  src: "../../fonts/Satoshi-Variable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { title?: string };
}>) {
  const headerText = params.title || "기본 헤더";
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${pretendard.variable} ${satoshi.variable}`}>
        <LenisProvider>
          <div className="relative overscroll-none">
            <MobileHeader text={headerText} session={session} />
            <main className="scrollbar-hide">{children}</main>
            <Footer />
          </div>
        </LenisProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
