import type { Metadata } from "next";
import localFont from "next/font/local";
import MobileHeader from "@/components/header/mobileheader";
import LenisProvider from "@/lib/lenisprovider";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { auth } from "@/auth";
import "./globals.css";

const pretendard = localFont({
  src: "../fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { title?: string };
}>) {
  const headerText = params.title || "기본 헤더";
  const session = await auth();

  return (
    <html lang="en">
      <body className={`${pretendard.variable} font-pretendard antialiased`}>
        <LenisProvider>
          <div className="relative bg-white shadow-2xl overscroll-none">
            <MobileHeader text={headerText} session={session} />
            <main className="flex flex-col scrollbar-hide">{children}</main>
          </div>
        </LenisProvider>
        <Analytics />
        <SpeedInsights />
      </body>
    </html>
  );
}
